name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      install-command: ''
      test-command: |
        env -u NIMBLE_COMMIT MAKE="make -j4" ARCH_OVERRIDE="$PLATFORM" NIM_COMMIT="$NIM_VERSION" \
          QUICK_AND_DIRTY_COMPILER=1 QUICK_AND_DIRTY_NIMBLE=1 CC=gcc V=1 \
          bash scripts/build_nim.sh nim-test csources dist/nimble NimBinaries-test
        nim-test/bin/nim --version
        nim-test/bin/nimble --version
